# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-vpc-peering-multi-account
  description: Terraform module to provision a VPC peering across multiple VPCs in different accounts by using multiple providers
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, vpc, aws, peering, multi-account, vpn, multi-provider




